import FunctionOne.FunctionOneThreeLayerNeuralNetwork as function_one_single_hidden
import FunctionOne.FunctionOneFourLayerNeuralNetwork as function_one_multi_hidden
import FunctionTwo.FunctionTwoThreeLayerNeuralNetwork as function_two_single_hidden
import FunctionTwo.FunctionTwoFourLayerNeuralNetwork as function_two_multi_hidden

# csv_writer = open("BestAndWorst.csv", "w")
# csv_writer.write("\nneurons, epochs, execution_time, mse")
# csv_writer.write("\nFunction_One_Single_Hidden_Worst")
# function_one_single_hidden_worst = function_one_single_hidden.NeuralNetwork(100, 1, csv_writer)
# function_one_single_hidden_worst.plot_error()
# function_one_single_hidden_worst.test_network()
# csv_writer.write("\nFunction_One_Single_Hidden_Best")
# function_one_single_hidden_best = function_one_single_hidden.NeuralNetwork(1000, 10, csv_writer)
# function_one_single_hidden_best.plot_error()
# function_one_single_hidden_best.test_network()
# csv_writer.write("\nFunction_One_Multi_Hidden_Worst")
# function_one_multi_hidden_worst = function_one_multi_hidden.NeuralNetwork(100, 1, csv_writer)
# function_one_multi_hidden_worst.plot_error()
# function_one_multi_hidden_worst.test_network()
# csv_writer.write("\nFunction_One_Multi_Hidden_Best")
# function_one_multi_hidden_best = function_one_multi_hidden.NeuralNetwork(1000, 10, csv_writer)
# function_one_multi_hidden_best.plot_error()
# function_one_multi_hidden_best.test_network()
# csv_writer.write("\nFunction_Two_Single_Hidden_Worst")
# function_two_single_hidden_worst = function_two_single_hidden.NeuralNetwork(100, 1, csv_writer)
# function_two_single_hidden_worst.plot_error()
# function_two_single_hidden_worst.test_network()
# csv_writer.write("\nFunction_Two_Single_Hidden_Best")
# function_two_single_hidden_best = function_two_single_hidden.NeuralNetwork(1000, 10, csv_writer)
# function_two_single_hidden_best.plot_error()
# function_two_single_hidden_best.test_network()
# csv_writer.write("\nFunction_Two_Multi_Hidden_Worst")
# function_two_multi_hidden_worst = function_two_multi_hidden.NeuralNetwork(100, 1, csv_writer)
# function_two_multi_hidden_worst.plot_error()
# function_two_multi_hidden_worst.test_network()
# csv_writer.write("\nFunction_Two_Multi_Hidden_Best")
# function_two_multi_hidden_best = function_two_multi_hidden.NeuralNetwork(1000, 10, csv_writer)
# function_two_multi_hidden_best.plot_error()
# function_two_multi_hidden_best.test_network()

csv_writer = open("ProjectStatistics.csv", "w")
csv_writer.write("Function_One_Single_Hidden")
csv_writer.write("\nneurons, epochs, execution_time, mse")
best_one = function_one_single_hidden.NeuralNetwork(900, 9, csv_writer)
best_one.plot_error()
best_one.test_network()
# function_one_single_hidden.NeuralNetwork(1000, 11, csv_writer)
# function_one_single_hidden.NeuralNetwork(2000, 12, csv_writer)
# function_one_single_hidden.NeuralNetwork(3000, 13, csv_writer)
# function_one_single_hidden.NeuralNetwork(4000, 14, csv_writer)
# function_one_single_hidden.NeuralNetwork(5000, 15, csv_writer)
# function_one_single_hidden.NeuralNetwork(6000, 16, csv_writer)
# function_one_single_hidden.NeuralNetwork(7000, 17, csv_writer)
# function_one_single_hidden.NeuralNetwork(8000, 18, csv_writer)
# function_one_single_hidden.NeuralNetwork(9000, 19, csv_writer)
# function_one_single_hidden.NeuralNetwork(10000, 20, csv_writer)
csv_writer.write("\nFunction_One_Multi_Hidden")
csv_writer.write("\nneurons, epochs, execution_time, mse")
best_two = function_one_multi_hidden.NeuralNetwork(7000, 17, csv_writer)
best_two.plot_error()
best_two.test_network()
# function_one_multi_hidden.NeuralNetwork(1000, 11, csv_writer)
# function_one_multi_hidden.NeuralNetwork(2000, 12, csv_writer)
# function_one_multi_hidden.NeuralNetwork(3000, 13, csv_writer)
# function_one_multi_hidden.NeuralNetwork(4000, 14, csv_writer)
# function_one_multi_hidden.NeuralNetwork(5000, 15, csv_writer)
# function_one_multi_hidden.NeuralNetwork(6000, 16, csv_writer)
# function_one_multi_hidden.NeuralNetwork(7000, 17, csv_writer)
# function_one_multi_hidden.NeuralNetwork(8000, 18, csv_writer)
# function_one_multi_hidden.NeuralNetwork(9000, 19, csv_writer)
# function_one_multi_hidden.NeuralNetwork(10000, 20, csv_writer)
csv_writer.write("\nFunction_Two_Single_Hidden")
csv_writer.write("\nneurons, epochs, execution_time, mse")
best_three = function_two_single_hidden.NeuralNetwork(100, 1, csv_writer)
best_three.plot_error()
best_three.test_network()
# function_two_single_hidden.NeuralNetwork(1000, 11, csv_writer)
# function_two_single_hidden.NeuralNetwork(2000, 12, csv_writer)
# function_two_single_hidden.NeuralNetwork(3000, 13, csv_writer)
# function_two_single_hidden.NeuralNetwork(4000, 14, csv_writer)
# function_two_single_hidden.NeuralNetwork(5000, 15, csv_writer)
# function_two_single_hidden.NeuralNetwork(6000, 16, csv_writer)
# function_two_single_hidden.NeuralNetwork(7000, 17, csv_writer)
# function_two_single_hidden.NeuralNetwork(8000, 18, csv_writer)
# function_two_single_hidden.NeuralNetwork(9000, 19, csv_writer)
# function_two_single_hidden.NeuralNetwork(10000, 20, csv_writer)
csv_writer.write("\nFunction_Two_Multi_Hidden")
csv_writer.write("\nneurons, epochs, execution_time, mse")
best_four = function_two_multi_hidden.NeuralNetwork(10000, 20, csv_writer)
best_four.plot_error()
best_four.test_network()
# function_two_multi_hidden.NeuralNetwork(1000, 11, csv_writer)
# function_two_multi_hidden.NeuralNetwork(2000, 12, csv_writer)
# function_two_multi_hidden.NeuralNetwork(3000, 13, csv_writer)
# function_two_multi_hidden.NeuralNetwork(4000, 14, csv_writer)
# function_two_multi_hidden.NeuralNetwork(5000, 15, csv_writer)
# function_two_multi_hidden.NeuralNetwork(6000, 16, csv_writer)
# function_two_multi_hidden.NeuralNetwork(7000, 17, csv_writer)
# function_two_multi_hidden.NeuralNetwork(8000, 18, csv_writer)
# function_two_multi_hidden.NeuralNetwork(9000, 19, csv_writer)
# function_two_multi_hidden.NeuralNetwork(10000, 20, csv_writer)
